# -*- coding: utf-8 -*-
{
    'name': 'Alfresco',
    'version': '1.0.0',
    'summary': 'Alfresco connection with Odoo',
    'category': 'API',
    'author': 'Planet-Odoo',
    'maintainer': 'Planet-Odoo',
    'company': 'Planet-Odoo',
    'website': '',
    'depends': ['base', 'purchase', 'sale', 'contacts', 'crm', 'stock', 'account', 'project', 'maintenance', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/alfresco_files_folder_view.xml',
        'wizard/alfresco_site_view.xml',
        'wizard/pop_up_wizard_view.xml',
        'view/alfresco_ui_view.xml',
        'view/alfresco_operation_view.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
