# -*- coding: utf-8 -*-
{
    'name': 'ALFRESCO - ODOO CONNECTOR',
    'version': '1.0.1',
    'summary': 'Alfresco connection with Odoo',
    'category': 'Extra Tools',
    'author': 'Planet-Odoo',
    'maintainer': 'Planet-Odoo',
    'company': 'Planet-Odoo',
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base', 'purchase', 'sale', 'contacts', 'crm', 'stock', 'account', 'project', 'maintenance', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'view/alfresco_operation_view.xml',
        'wizard/alfresco_files_folder_view.xml',
        'wizard/alfresco_site_view.xml',
        'wizard/pop_up_wizard_view.xml',
        'view/alfresco_ui_view.xml',
    ],
    'images': [],
    'license': 'AGPL-3',
    'price': "500",
    'currency': "EUR",
    'qweb': ['static/src/xml/*.xml'],
    'js': ['static/src/js/*.js'],
    'images': ["static/description/planeicon.png"],
    'installable': True,
    'application': True,
    'auto_install': False,
}
